### ISSUE TITLE
BufferUnderflowException in BitcoinBlockReader.readBlock

### ISSUE THREAD

**Issue by PhillHenry** [ZuInnoTe/hadoopcryptoledger#17]
Downloaded the entire blockchain using the canonical bitcoind, copied it to an Hadoop (2.7.3) on AWS and ran a Spark job over the data. Was OK for about 900 partitions then failed with:

Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
	at org.zuinnote.hadoop.bitcoin.format.common.BitcoinBlockReader.readBlock(BitcoinBlockReader.java:115)
	at org.zuinnote.hadoop.bitcoin.format.mapreduce.BitcoinBlockRecordReader.nextKeyValue(BitcoinBlockRecordReader.java:83)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:207)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:1126)
	at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:1132)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
.
.

Using version 1.0.4.

**Comment by jornfranke** [comment]
thank you for reporting. I have some questions so I can do a more detailed investigation:
- Was the Bitcoin Blockchain fetched this month?
- Do you know at which block it happened? Not sure how to interpret partition 900, is it the 900 blockchain file, ie blk00900.dat?
- did you upload only blk*.dat files and not rev*.dat files?

There are several possibilities:
- Partition 900 contains an invalid block that has not yet been verified by Bitcoin core. This could be if partition 900 is the most recent file updated by Bitcoin core.
- there are some changes in the Bitcoin protocol or the client that has some effects on the block storage. I will investigate here.

**Comment by jornfranke** [comment]
And another question: Can you you please look in the executor and driver logs if there is another exception beforehand?

**Comment by PhillHenry** [comment]
PEBCAK, I'm afraid. I ran it with hdfs:/blocks/*.dat rather than hdfs:/blocks/blk*.dat. My bad.

It only remains for me to apologize for wasting your time and to thank you for donating this excellent project to the community.

BTW, Partition blk00900.dat parsed fine.

Finally, in answer to your question, I downloaded the blockchain last week.

**Comment by jornfranke** [comment]
No worries thank for the quick reply. We always try to improve the software and we are happy to exchange about it!

**Comment by eremeev** [comment]
Hi,
I have just encountered with the same problem on file blk00975.dat, and it looks like all files since blk*975.dat cannot be parsed with BitcoinBlockFileInputFormat.
```
Caused by: java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at org.zuinnote.hadoop.bitcoin.format.common.BitcoinBlockReader.parseTransactions(BitcoinBlockReader.java:183)
	at org.zuinnote.hadoop.bitcoin.format.common.BitcoinBlockReader.readBlock(BitcoinBlockReader.java:130)
	at org.zuinnote.hadoop.bitcoin.format.mapreduce.BitcoinBlockRecordReader.nextKeyValue(BitcoinBlockRecordReader.java:83)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:207)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:918)
```

**Comment by jornfranke** [comment]
Yes see the issue on segwit support - it is being worked on.
